use anchor_lang::prelude::*;
use anchor_lang::solana_program::program::invoke_signed;
use anchor_lang::solana_program::program::invoke;
use spl_token_2022::{
    self,
    extension::ExtensionType,
    instruction as token_instruction,
};

use crate::constants::*;
use crate::error::StablecoinError;
use crate::events::StablecoinInitialized;
use crate::state::*;

#[derive(AnchorSerialize, AnchorDeserialize)]
pub struct InitializeParams {
    pub name: String,
    pub symbol: String,
    pub uri: String,
    pub decimals: u8,
    pub enable_permanent_delegate: bool,
    pub enable_transfer_hook: bool,
    pub enable_confidential_transfer: bool,
    pub enable_allowlist: bool,
}

#[derive(Accounts)]
#[instruction(params: InitializeParams)]
pub struct Initialize<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,

    /// The master authority for this stablecoin.
    pub authority: Signer<'info>,

    /// The stablecoin configuration PDA — derived from the mint keypair.
    #[account(
        init,
        payer = payer,
        space = StablecoinConfig::LEN,
        seeds = [StablecoinConfig::SEED_PREFIX, mint.key().as_ref()],
        bump,
    )]
    pub config: Box<Account<'info, StablecoinConfig>>,

    /// The stablecoin Token-2022 mint. A fresh keypair generated by the client.
    /// Initialized via CPI for dynamic extension selection.
    /// CHECK: Validated during CPI initialization — we create this account with calculated
    /// space for the selected extensions and initialize it with Token-2022.
    #[account(mut, signer)]
    pub mint: UncheckedAccount<'info>,

    /// Role configuration PDA.
    #[account(
        init,
        payer = payer,
        space = RoleConfig::LEN,
        seeds = [RoleConfig::SEED_PREFIX, config.key().as_ref()],
        bump,
    )]
    pub roles: Box<Account<'info, RoleConfig>>,

    /// The transfer hook program (required if enable_transfer_hook is true).
    /// CHECK: Validated by constraint when transfer hook is enabled.
    pub transfer_hook_program: Option<UncheckedAccount<'info>>,

    /// Token-2022 program.
    /// CHECK: Constrained to the Token-2022 program ID.
    #[account(address = spl_token_2022::ID)]
    pub token_program: UncheckedAccount<'info>,

    pub system_program: Program<'info, System>,
    pub rent: Sysvar<'info, Rent>,
}

pub fn handler(ctx: Context<Initialize>, params: InitializeParams) -> Result<()> {
    // --- Validation ---
    require!(params.decimals <= MAX_DECIMALS, StablecoinError::InvalidDecimals);
    require!(params.name.len() <= MAX_NAME_LEN, StablecoinError::NameTooLong);
    require!(params.symbol.len() <= MAX_SYMBOL_LEN, StablecoinError::SymbolTooLong);
    require!(params.uri.len() <= MAX_URI_LEN, StablecoinError::UriTooLong);

    if params.enable_transfer_hook {
        require!(
            ctx.accounts.transfer_hook_program.is_some(),
            StablecoinError::TransferHookNotEnabled
        );
    }

    let config_key = ctx.accounts.config.key();
    let mint_key = ctx.accounts.mint.key();
    let config_bump = ctx.bumps.config;

    // --- Determine extensions ---
    let mut extensions = vec![ExtensionType::MetadataPointer];

    if params.enable_permanent_delegate {
        extensions.push(ExtensionType::PermanentDelegate);
    }
    if params.enable_transfer_hook {
        extensions.push(ExtensionType::TransferHook);
    }
    if params.enable_confidential_transfer {
        extensions.push(ExtensionType::ConfidentialTransferMint);
    }

    // --- Calculate mint account space ---
    // Only include the extension type headers. The actual metadata content
    // will be added by Token-2022's metadata initialize, which reallocates the account.
    let mint_space = ExtensionType::try_calculate_account_len::<spl_token_2022::state::Mint>(
        &extensions,
    )
    .map_err(|_| StablecoinError::Overflow)?;

    // Pre-calculate total space including metadata for lamport calculation.
    // Token-2022's metadata init will realloc the account but needs sufficient lamports.
    // Metadata TLV: discriminator(4) + update_authority(32) + mint(32) +
    //   name(4+len) + symbol(4+len) + uri(4+len) + additional_metadata(4)
    let metadata_space = 4 + 32 + 32
        + 4 + params.name.len()
        + 4 + params.symbol.len()
        + 4 + params.uri.len()
        + 4;

    // Fund the mint with enough lamports for the final size (extensions + metadata),
    // but create the account with only the extension space.
    let total_space = mint_space + metadata_space;
    let lamports = Rent::get()?.minimum_balance(total_space);

    // Config PDA signer seeds (config is mint authority).
    let config_seeds: &[&[u8]] = &[
        StablecoinConfig::SEED_PREFIX,
        mint_key.as_ref(),
        &[config_bump],
    ];

    // --- Create mint account (the mint keypair signs this) ---
    // Space is only for extensions; metadata init will realloc.
    // Lamports cover the full final size so Token-2022 can realloc without funding issues.
    invoke(
        &anchor_lang::solana_program::system_instruction::create_account(
            &ctx.accounts.payer.key(),
            &mint_key,
            lamports,
            mint_space as u64,
            &spl_token_2022::ID,
        ),
        &[
            ctx.accounts.payer.to_account_info(),
            ctx.accounts.mint.to_account_info(),
            ctx.accounts.system_program.to_account_info(),
        ],
    )?;

    // --- Initialize metadata pointer (must be before InitializeMint) ---
    invoke(
        &spl_token_2022::extension::metadata_pointer::instruction::initialize(
            &spl_token_2022::ID,
            &mint_key,
            Some(config_key),
            Some(mint_key),
        )?,
        &[ctx.accounts.mint.to_account_info()],
    )?;

    // --- Initialize permanent delegate if enabled (must be before InitializeMint) ---
    if params.enable_permanent_delegate {
        invoke(
            &token_instruction::initialize_permanent_delegate(
                &spl_token_2022::ID,
                &mint_key,
                &config_key,
            )?,
            &[ctx.accounts.mint.to_account_info()],
        )?;
    }

    // --- Initialize transfer hook if enabled (must be before InitializeMint) ---
    if params.enable_transfer_hook {
        let hook_program = ctx
            .accounts
            .transfer_hook_program
            .as_ref()
            .unwrap();

        invoke(
            &spl_token_2022::extension::transfer_hook::instruction::initialize(
                &spl_token_2022::ID,
                &mint_key,
                Some(config_key),
                Some(hook_program.key()),
            )?,
            &[ctx.accounts.mint.to_account_info()],
        )?;
    }

    // --- Initialize confidential transfer extension if enabled (SSS-3) ---
    if params.enable_confidential_transfer {
        invoke(
            &spl_token_2022::extension::confidential_transfer::instruction::initialize_mint(
                &spl_token_2022::ID,
                &mint_key,
                Some(config_key),  // authority
                true,              // auto-approve new accounts
                None,              // no auditor ElGamal pubkey (can be set later)
            )?,
            &[ctx.accounts.mint.to_account_info()],
        )?;
    }

    // --- Initialize mint (after all extensions) ---
    invoke(
        &token_instruction::initialize_mint2(
            &spl_token_2022::ID,
            &mint_key,
            &config_key,       // mint authority = config PDA
            Some(&config_key), // freeze authority = config PDA
            params.decimals,
        )?,
        &[ctx.accounts.mint.to_account_info()],
    )?;

    // --- Initialize token metadata (after InitializeMint, requires config PDA signature) ---
    invoke_signed(
        &spl_token_metadata_interface::instruction::initialize(
            &spl_token_2022::ID,
            &mint_key,
            &config_key,       // update authority
            &mint_key,         // metadata account (the mint itself)
            &config_key,       // mint authority
            params.name.clone(),
            params.symbol.clone(),
            params.uri.clone(),
        ),
        &[
            ctx.accounts.mint.to_account_info(),
            ctx.accounts.config.to_account_info(),
        ],
        &[config_seeds],
    )?;

    // --- Initialize config state ---
    let config = &mut ctx.accounts.config;
    config.master_authority = ctx.accounts.authority.key();
    config.pending_authority = Pubkey::default();
    config.mint = mint_key;
    config.decimals = params.decimals;
    config.enable_permanent_delegate = params.enable_permanent_delegate;
    config.enable_transfer_hook = params.enable_transfer_hook;
    config.is_paused = false;
    config.total_minted = 0;
    config.total_burned = 0;
    config.bump = config_bump;
    config.enable_confidential_transfer = params.enable_confidential_transfer;
    config.enable_allowlist = params.enable_allowlist;
    config._reserved = [0u8; 126];

    // --- Initialize roles (all roles start as master authority) ---
    let roles = &mut ctx.accounts.roles;
    roles.stablecoin_config = config.key();
    roles.pauser = ctx.accounts.authority.key();
    roles.freezer = ctx.accounts.authority.key();
    roles.blacklister = ctx.accounts.authority.key();
    roles.seizer = ctx.accounts.authority.key();
    roles.bump = ctx.bumps.roles;

    emit!(StablecoinInitialized {
        config: config.key(),
        mint: mint_key,
        authority: ctx.accounts.authority.key(),
        enable_permanent_delegate: params.enable_permanent_delegate,
        enable_transfer_hook: params.enable_transfer_hook,
        enable_confidential_transfer: params.enable_confidential_transfer,
        enable_allowlist: params.enable_allowlist,
        decimals: params.decimals,
        timestamp: Clock::get()?.unix_timestamp,
    });

    Ok(())
}
